import { ApiClient } from '../core/ApiClient';
import { PromptEngine } from '../llm/PromptEngine';
import { Case, EvidenceSubmission } from '../types';
import { EventEmitter } from 'events';

/**
 * JudicialState: Tracks the lifecycle of a case from the perspective of an Arbiter.
 */
export enum JudicialState {
    IDLE = 'IDLE',
    ASSIGNED = 'ASSIGNED',
    DISCOVERY = 'DISCOVERY',
    DELIBERATION = 'DELIBERATION',
    ISSUING_VERDICT = 'ISSUING_VERDICT',
    COMPLETED = 'COMPLETED',
    ERROR = 'ERROR'
}

/**
 * ArbiterKernel: The high-density orchestration layer for Autonomous AI Judges.
 * 
 * This class is responsible for:
 * 1. Managing the state transition of judicial tasks.
 * 2. Orchestrating parallel evidence fetching and verification.
 * 3. Interfacing with Agent-specific logic for decision making.
 * 4. Ensuring protocol compliance and verdict finality.
 */
export class ArbiterKernel extends EventEmitter {
    private currentState: JudicialState = JudicialState.IDLE;
    private activeCase?: Case;
    private evidenceBuffer: EvidenceSubmission[] = [];
    private startTime?: number;

    constructor(
        private readonly apiClient: ApiClient,
        private readonly agentId: string
    ) {
        super();
    }

    /**
     * Initializes a judicial workflow for a specific case assignment.
     * 
     * @param caseData The case metadata provided by the protocol.
     */
    public async ingestAssignment(caseData: Case): Promise<void> {
        this.transition(JudicialState.ASSIGNED);
        this.activeCase = caseData;
        this.startTime = Date.now();
        this.emit('workflow:started', { caseId: caseData.case_id });

        try {
            await this.executeDiscovery();
        } catch (error) {
            this.handleFailure(error as Error);
        }
    }

    /**
     * Discovery Phase: Parallelized fetching of all evidence and audit trails.
     */
    private async executeDiscovery(): Promise<void> {
        if (!this.activeCase) throw new Error("No active case in context.");
        this.transition(JudicialState.DISCOVERY);

        const caseId = this.activeCase.case_id || this.activeCase.id;

        // Parallel fetch of Evidence and Context
        const [evidence] = await Promise.all([
            this.apiClient.get<EvidenceSubmission[]>(`/cases/${caseId}/evidence`)
            // auditService.getTrail(caseId) 
        ]);

        this.evidenceBuffer = evidence;
        this.emit('discovery:complete', { count: evidence.length });

        await this.startDeliberation();
    }

    /**
     * Deliberation Phase: Preparing data for the AI model.
     */
    private async startDeliberation(): Promise<void> {
        this.transition(JudicialState.DELIBERATION);

        if (!this.activeCase) return;

        // Construct the "Judge's Dossier"
        const dossier = PromptEngine.synthesize(this.activeCase, this.evidenceBuffer);

        // Notify the Agent implementation that data is ready for LLM consumption
        this.emit('deliberation:ready', {
            dossier,
            rawCase: this.activeCase,
            rawEvidence: this.evidenceBuffer
        });
    }

    /**
     * Finalizes the judicial process by submitting the verdict to the protocol.
     * 
     * @param ruling The final decision (e.g., 'plaintiff', 'defendant', 'dismissed').
     * @param rationale A detailed explanation (generated by the AI).
     */
    public async submitFinalVerdict(ruling: string, rationale: string): Promise<void> {
        if (this.currentState !== JudicialState.DELIBERATION) {
            throw new Error(`Invalid state for verdict submission: ${this.currentState}`);
        }

        this.transition(JudicialState.ISSUING_VERDICT);

        try {
            const caseId = this.activeCase?.case_id || this.activeCase?.id;

            const payload = {
                ruling,
                rationale,
                judgeId: this.agentId,
                timestamp: Date.now(),
            };

            await this.apiClient.post(`/cases/${caseId}/verdict`, payload);

            this.transition(JudicialState.COMPLETED);
            this.emit('workflow:completed', { duration: Date.now() - (this.startTime || 0) });

            this.cleanup();
        } catch (error) {
            this.handleFailure(error as Error);
        }
    }

    /**
     * Internal state transitioner with audit logging.
     */
    private transition(newState: JudicialState): void {
        const oldState = this.currentState;
        this.currentState = newState;
        // console.debug(`[ArbiterKernel] Transition: ${oldState} -> ${newState}`);
        this.emit('state:changed', { from: oldState, to: newState });
    }

    private handleFailure(error: Error): void {
        this.transition(JudicialState.ERROR);
        this.emit('workflow:failed', { error: error.message });
        console.error(`[ArbiterKernel] Terminal failure: ${error.message}`);
    }

    private cleanup(): void {
        this.activeCase = undefined;
        this.evidenceBuffer = [];
        this.startTime = undefined;
        this.currentState = JudicialState.IDLE;
    }

    // --- Accessors ---

    public getState(): JudicialState {
        return this.currentState;
    }

    public getActiveCase(): Case | undefined {
        return this.activeCase;
    }
}
